### ISSUE TITLE
コメント削除ボタン用のstyleを追加

### ISSUE THREAD

**Issue by JunichiIto** [JunichiIto/fjord-books_app-2023#23]
````css
li form {
  display: inline;
}

li form button[type="submit"] {
  font-size: 11px;
  padding: 1px;
}
````

<img width="311" alt="Screenshot 2023-01-24 at 10 06 58" src="https://user-images.githubusercontent.com/1148320/214192240-2cd35e3c-67c3-4847-a9f0-b74b3b8bee19.png">
